#!/usr/bin/env python3
"""Deterministic Stage 01 local semantics.

Stage 01 keeps the codex-first artifact chain, but the actual structured output
is generated locally from the locked brief to avoid recursive Codex CLI
deadlocks in the desktop environment.
"""
from __future__ import annotations

from typing import Any

from pipeline_blueprints import build_stage01_script, normal_brief


def _subject_label(name: str) -> str:
    text = str(name or "").strip()
    replacements = {
        "年轻的亚洲女性": "亚洲年轻女性",
        "年轻的女性": "年轻女性",
        "年轻的女生": "年轻女生",
        "年轻的女孩": "年轻女孩",
    }
    return replacements.get(text, text or "人物")


def _identity_anchor(character: dict[str, Any], brief: dict[str, Any], script_payload: dict[str, Any]) -> str:
    normalized = normal_brief(brief)
    name = str(character.get("name") or "").strip()
    age = str(character.get("age") or "").strip()
    role = str(character.get("role") or "main").strip()
    idea = str(normalized.get("idea") or "").strip()
    lead = _subject_label(name or str(((script_payload.get("creative_contract") or {}).get("subject")) or "").strip())
    age_text = f"{age}，" if age else ""
    role_text = "" if role == "main" else f"（{role}）"
    if any(token in idea for token in ["黄昏", "傍晚", "落日"]) and any(token in idea for token in ["海滩", "海边"]) and any(token in idea for token in ["散步", "放空"]):
        return f"{age_text}在黄昏海边独自散步、想把心事慢慢放下的{lead}{role_text}".strip("，")
    if "雨夜" in idea and "便利店" in idea and "伞" in idea:
        return f"{age_text}在雨夜便利店门口把最后一把伞递出去的{lead}{role_text}".strip("，")
    if any(token in idea for token in ["职业危机", "精神内耗"]):
        return f"{age_text}被工作和内耗拖得太久、正试着重新找回呼吸的{lead}{role_text}".strip("，")
    state = str(script_payload.get("protagonist_state") or "").strip()
    for prefix in [name, lead]:
        if prefix and state.startswith(prefix):
            state = state[len(prefix):].lstrip("，,。 ")
            break
    state = state.replace("看起来", "", 1).replace("正处在", "", 1).strip("，,。 ")
    if state:
        return f"{age_text}{state}的{lead}{role_text}".strip("，")
    return f"{age_text}{lead}{role_text}".strip("，")


def _beat_id(index: int) -> str:
    return f"B{index + 1:02d}"


def build_stage01_llm_output(
    brief: dict[str, Any],
    prompt_packet: dict[str, Any] | None = None,
    repair_packet: dict[str, Any] | None = None,
) -> dict[str, Any]:
    script_payload = build_stage01_script(brief)
    duration_beats = list(((script_payload.get("duration_plan") or {}).get("beats")) or [])
    sections = list(((script_payload.get("script") or {}).get("sections")) or [])
    characters = []
    for character in list(script_payload.get("characters") or []):
        if not isinstance(character, dict):
            continue
        characters.append({
            "name": str(character.get("name") or "").strip(),
            "age": str(character.get("age") or "").strip(),
            "role": str(character.get("role") or "main").strip(),
            "identity_anchor": _identity_anchor(character, brief, script_payload),
        })

    beats = []
    beat_total = max(len(duration_beats), len(sections))
    for idx in range(beat_total):
        beat = duration_beats[idx] if idx < len(duration_beats) and isinstance(duration_beats[idx], dict) else {}
        section = sections[idx] if idx < len(sections) and isinstance(sections[idx], dict) else {}
        beats.append({
            "beat_id": str(beat.get("beat_id") or _beat_id(idx)),
            "start": str(beat.get("start") or "").strip(),
            "end": str(beat.get("end") or "").strip(),
            "summary": str(beat.get("summary") or "").strip(),
            "emotion": str(beat.get("emotion") or "").strip(),
            "visual": str(section.get("visual") or "").strip(),
            "composition_focus": str(section.get("composition_focus") or "").strip(),
            "voiceover": str(section.get("voiceover") or "").strip(),
            "dialogue": str(section.get("dialogue") or "").strip(),
            "music_cue": str(section.get("music_cue") or "").strip(),
        })

    self_check = dict(script_payload.get("self_check") or {})
    notes = list(self_check.get("notes") or [])
    notes.append("Generated by Stage 01 local semantics from locked brief.")
    if prompt_packet:
        notes.append(f"Prompt packet preserved: {prompt_packet.get('packet_version') or 'unknown'}")
    if repair_packet:
        notes.append("Repair loop requested deterministic regeneration from the same locked brief.")
    self_check["notes"] = notes

    return {
        "title_candidates": list(script_payload.get("title_candidates") or [script_payload.get("title")]),
        "selected_title": str(script_payload.get("title") or "").strip(),
        "logline": str(script_payload.get("logline") or "").strip(),
        "theme": str(script_payload.get("theme") or "").strip(),
        "protagonist_state": str(script_payload.get("protagonist_state") or "").strip(),
        "narrative_movement": str(script_payload.get("narrative_movement") or "").strip(),
        "ending_direction": str(script_payload.get("ending_direction") or "").strip(),
        "avoid": list(script_payload.get("avoid") or []),
        "characters": characters,
        "settings": list(script_payload.get("settings") or []),
        "beats": beats,
        "self_check": self_check,
    }
